from tkinter import *
from PIL import ImageTk,Image
import tkinter as tk
import cv2
import math
import argparse
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

parser=argparse.ArgumentParser()
parser.add_argument('--image')

args=parser.parse_args()

faceProto="opencv_face_detector.pbtxt"
faceModel="opencv_face_detector_uint8.pb"
ageProto="age_deploy.prototxt"
ageModel="age_net.caffemodel"
genderProto="gender_deploy.prototxt"
genderModel="gender_net.caffemodel"

MODEL_MEAN_VALUES=(78.4263377603, 87.7689143744, 114.895847746)
ageList=['(0 to 2)', '(3 to 7)', '(8 to 14)', '(15 to 21)', '(22 to 32)', '(33 to 45)', '(46 to 59)', '(60 and above)']
genderList=['Male','Female']

faceNet=cv2.dnn.readNet(faceModel,faceProto)
ageNet=cv2.dnn.readNet(ageModel,ageProto)
genderNet=cv2.dnn.readNet(genderModel,genderProto)

def highlightFace(net, frame, conf_threshold=0.7):
    frameOpencvDnn=frame.copy()
    frameHeight=frameOpencvDnn.shape[0]
    frameWidth=frameOpencvDnn.shape[1]
    blob=cv2.dnn.blobFromImage(frameOpencvDnn, 1.0, (300, 300), [104, 117, 123], True, False)

    net.setInput(blob)
    detections=net.forward()
    faceBoxes=[]
    for i in range(detections.shape[2]):
        confidence=detections[0,0,i,2]
        if confidence>conf_threshold:
            x1=int(detections[0,0,i,3]*frameWidth)
            y1=int(detections[0,0,i,4]*frameHeight)
            x2=int(detections[0,0,i,5]*frameWidth)
            y2=int(detections[0,0,i,6]*frameHeight)
            faceBoxes.append([x1,y1,x2,y2])
            cv2.rectangle(frameOpencvDnn, (x1,y1), (x2,y2), (0,0,255), int(round(frameHeight/150)), 8)
    return frameOpencvDnn,faceBoxes

video=cv2.VideoCapture(args.image if args.image else 0)
padding=20
while cv2.waitKey(1)<0:
    hasFrame,frame=video.read()
    if not hasFrame:
        cv2.waitKey()
        break

    resultImg,faceBoxes=highlightFace(faceNet,frame)
    if not faceBoxes:
        print("No face detected")

    for faceBox in faceBoxes:
        face=frame[max(0,faceBox[1]-padding):
                   min(faceBox[3]+padding,frame.shape[0]-1),max(0,faceBox[0]-padding)
                   :min(faceBox[2]+padding, frame.shape[1]-1)]

        blob=cv2.dnn.blobFromImage(face, 1.0, (227,227), MODEL_MEAN_VALUES, swapRB=False)
        genderNet.setInput(blob)
        genderPreds=genderNet.forward()
        
        gender=genderList[genderPreds[0].argmax()]
        g=gender
        print(f'Gender: {gender}')

        ageNet.setInput(blob)
        agePreds=ageNet.forward()
        age=ageList[agePreds[0].argmax()]
        a = age
        print(f'Age: {age[1:-1]} years')



        cv2.putText(resultImg, f'{gender}, {age}', (faceBox[0], faceBox[1]-10), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,255), 2, cv2.LINE_AA)
        cv2.imshow("Detecting age and gender", resultImg)
        


dataframe = pd.read_csv('project.csv',)  

print('\n\nStructure of Data\n\n')
print(dataframe.head(10))
print("\n") 
print(dataframe.describe())

print('\n\nAnalysis of Data\n\n')
print("\n")
print(dataframe.dtypes)
print("\n")
print(dataframe['Age'].value_counts())
print(dataframe['Gender'].value_counts())
print(dataframe['Output'].value_counts())

dataframe['Output']=dataframe['Output'].replace('NYKA','Nyka')
dataframe['Output']=dataframe['Output'].replace('LEVI','Levi')
dataframe['Output']=dataframe['Output'].replace('Levi ','Levi')
dataframe['Output']=dataframe['Output'].replace('Nike ','Nike')
dataframe['Output']=dataframe['Output'].replace('Ptr England','Peter England')
dataframe['Output']=dataframe['Output'].replace('Vans','Van Heusen')
dataframe['Output']=dataframe['Output'].replace('Thai Spa','Myo Thai Spa')

dataframe['Age']=dataframe['Age'].replace('25','22 to 32')
dataframe['Age']=dataframe['Age'].replace('28','22 to 32')
dataframe['Age']=dataframe['Age'].replace('36','33 to 45')
dataframe['Age']=dataframe['Age'].replace('49','46 to 59')
dataframe['Age']=dataframe['Age'].replace('78','60 and above')
dataframe['Age']=dataframe['Age'].replace('3 to 7 ','3 to 7')

dataframe['Gender']=dataframe['Gender'].replace('M','Male')
dataframe['Gender']=dataframe['Gender'].replace('F','Female')


print(dataframe['Gender'].value_counts())
print(dataframe['Age'].value_counts())
print(dataframe['Output'].value_counts())


print('\n\nUnivariate Analysis\n\n')
fig=plt.figure(figsize=(35,20))
cols=5
rows=np.ceil(float(dataframe.shape[1])/cols)
for i,column in enumerate(dataframe.columns):
    ax=fig.add_subplot(rows,cols,i+1)
    ax.set_title(column)
    if dataframe.dtypes[column]==np.object:
        dataframe[column].value_counts().plot(kind='bar',axes=ax)
    else:
        dataframe[column].hist(axes=ax)
        plt.xticks(rotation='vertical')
plt.subplots_adjust(hspace=0.7,wspace=0.2)
        
z=dataframe.drop(columns=['Output'])
X = pd.get_dummies(z)

le = preprocessing.LabelEncoder()    
dataframe['Output']=le.fit_transform(dataframe['Output'])   
y=dataframe['Output']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy Score on test data: ", 100* accuracy_score(y_test,y_pred))

rfc = RandomForestClassifier(criterion='gini',max_features= 'auto')
rfc.fit(X_train,y_train)
y_pred_rf = rfc.predict(X_test)
print("Accuracy Score on test data: ", 100* accuracy_score(y_test,y_pred))

print("\n\n")
c=a[1:-1]
d=g
dict={'Age':[c],'Gender':[d]}
df1=pd.DataFrame(dict)
df2=pd.concat([z,df1])

temp=pd.get_dummies(df2)

X1=temp.iloc[-1,:]

X1=X1.to_frame()

X1=X1.T

y1=clf.predict(X1)

Y=le.inverse_transform(y1)
print(Y)
Y=str(Y)
Y=Y[2:-2]
print(Y)

dict={'Age':[c],'Gender':[d],'Output':[Y]}
df=pd.DataFrame(dict)
print(df)
print("\n\n\n\n\n\n\n\n\n\n\n\n")


# Interface-------->>>>>
root=tk.Tk()
root.title("BRAND")
canvas = tk.Canvas(root,height=700,width=700,bg='black')
canvas.pack()
line = canvas.create_line(0, 300,700 , 300,fill="white")
canvas.create_text(135,30,fill="white",font="Montserrat 20 bold",text="Recommendation : ")
canvas.create_text(100,310,fill="white",font="Montserrat 15 bold",text="Popular Products : ")
if(d=="Male"):
    if(c=="0 to 2"):
        if(Y=="Hamleys"):
             img1 = ImageTk.PhotoImage(file="logos/AliAligator.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/IggyIguana.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/SunnySea.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/StaceyShark.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/ReginaldRhino.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Spiderman.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Hamleys.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Ali Aligator")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Iggy Iguana")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sunny Sea")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="StaceyShark")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Reginald Rhino")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Spiderman")
             
        elif(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/FarmRider.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Commander.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Babyhug.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/RideonRed.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/ReginaldRhino.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Spiderman.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Farm Rider")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Commander")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Babyhug")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Rideon Red")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Reginald Rhino")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Spiderman")
        elif(Y=="Mothercare"):
             img1 = ImageTk.PhotoImage(file="logos/Safari.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/penguinpajamas.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/explore.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/teddybearpajamas.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/sweetdreams.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/disneyshirt.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Mothercare.jpg")
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Safari")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Penguin Pajamas")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Explore")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Teddybear Pajamas")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Sweetdreams")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Disneyshirt")
             
             
             
    elif(c=="3 to 7"):
        if(Y=="Hamleys"):
             img1 = ImageTk.PhotoImage(file="logos/Spiderman.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Unojunior.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Harrypotter.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jenga.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Connect4.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Mindthegap.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Hamleys.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Spiderman")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Unojunior")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Harry Potter")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jenga")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Connect4")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Mind the gap")
        elif(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/Gunshock.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Loopcar.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Flipcar.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Pokibot.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Battlespider.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Dinosaurs.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Gunshock")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Loopcar")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Flipcar")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Pokibot")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Battlespider")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Dinosaurs")
        elif(Y=="McDonalds"):
             img1 = ImageTk.PhotoImage(file="logos/Happymealtoys.jpg")
             canvas.create_image(110, 380, anchor='nw', image=img1)
             img = ImageTk.PhotoImage(file="logos/comp/McDonalds.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(310,685,fill="white",font="Montserrat 10 bold",text="Happymeal Toys")
             
             
   
    elif(c=="8 to 14"):
        if(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/Roboticarm.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Microtitans.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Battlebots.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Silverlitrobot.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Nanospace.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Spiderman.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Robotic arm")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Microtitans")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Battlebots")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Silverlit robot")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Nanospace")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Spiderman")
             
        elif(Y=="McDonalds"):
             img1 = ImageTk.PhotoImage(file="logos/Softserve.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img1)
             img5 = ImageTk.PhotoImage(file="logos/Cokefloat.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img = ImageTk.PhotoImage(file="logos/comp/McDonalds.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(310,685,fill="white",font="Montserrat 10 bold",text="Happymeal Toys")
        elif(Y=="Max"):
             img1 = ImageTk.PhotoImage(file="logos/Solidshorts.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Sleeveless.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Batmancap.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Starwarscap.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Casualtrousers.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Jeans.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Max.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Solid shorts")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Sleeveless")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Batman cap")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Starwars cap")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Casual trousers")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Jeans")

    elif(c=="15 to 21"):
        if(Y=="Adidas"):
             img1 = ImageTk.PhotoImage(file="logos/Krayshoes.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Drogoshoes.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Runningshorts.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Visor.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Climalitecap.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Trainingtee.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Adidas.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Kray shoes")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Drogo shoes")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Running shorts")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Visor")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Climalite cap")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Training tee")
        elif(Y=="Inox"):
             img1 = ImageTk.PhotoImage(file="logos/Movieludo.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Movieblackwidow.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/popcorn.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Combo.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/Inox.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Movie Ludo")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Movie Blackwidow")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Popcorn")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Combo")
        elif(Y=="Smaash"):
             img1 = ImageTk.PhotoImage(file="logos/Cricket.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Bowling.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Keeper.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Arcade.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Fingercoaster.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Trampolinepark.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Smaash.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Cricket")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Bowling")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Keeper")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Arcade")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Fingercoaster")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Trampoline park")
    
    elif(c=="22 to 32"):
        if(Y=="Nike"):
             img1 = ImageTk.PhotoImage(file="logos/Phantomrun.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Airmax.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Sportswear.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jordan23.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Lakers.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Proflex.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Nike.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Phantom run")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Airmax")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sportswear")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jordan23")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Lakers")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Proflex")
        elif(Y=="Levi"):
             img1 = ImageTk.PhotoImage(file="logos/Pocketshirt.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Truckerjacket.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Sweatshirt.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Lpack.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/501belt.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Serifcap.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Levis.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Pocketshirt")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Trucker jacket")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sweatshirt")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="L pack")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="501 belt")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Serifcap")
        elif(Y=="H&M"):
             img1 = ImageTk.PhotoImage(file="logos/Printedtshirt.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Canvas.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Nasa.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Hoodie.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Joggers.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Swimshorts.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/H&M.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Printedt shirt")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Canvas")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Nasa")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Hoodie")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Joggers")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Swimshorts")
    
    elif(c=="33 to 45"):
        if(Y=="Levi"):
             img1 = ImageTk.PhotoImage(file="logos/Sunsetpocket.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Reversible.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Sweatshirt.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Lpack.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/501belt.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Serifcap.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Levis.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Sunset pocket")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Reversible")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sweatshirt")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Lpack")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="501 belt")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Serifcap")
        elif(Y=="Van Heusen"):
             img1 = ImageTk.PhotoImage(file="logos/Vdot.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Laceupshoes.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Pinkshirt.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Vdotjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/VanHeusen.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Vdot")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Laceup shoes")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Pink shirt")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Vdot jeans")
        elif(Y=="Inox"):
             img1 = ImageTk.PhotoImage(file="logos/Movieludo.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Movieblackwidow.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/popcorn.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Combo.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/Inox.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Movie Ludo")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Movie Blackwidow")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Popcorn")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Combo")
    
    elif(c=="46 to 59"):
        if(Y=="Peter England"):
             img1 = ImageTk.PhotoImage(file="logos/Redshirt.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Halfsleeves.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Navytie.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Brownsunglasses.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Navyjeans.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Olivewallet.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/PeterEngland.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Red shirt")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Halfsleeves")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Navy tie")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Brown sunglasses")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Navy jeans")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Olive wallet")
        elif(Y=="Van Heusen"):
             img1 = ImageTk.PhotoImage(file="logos/Suit.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Trackpant.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Greysweater.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Vdotjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/VanHeusen.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Suit")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Trackpant")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Greysweater")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Vdot jeans")
        elif(Y=="Starbucks"):
             img1 = ImageTk.PhotoImage(file="logos/Honeylatte.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Midnightmocha.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Mangopopper.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Kiwismoothie.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/Starbucks.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Honey latte")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Midnight mocha")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Mango popper")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Kiwi smoothie")
             
        
    
    elif(c=="60 and above"):
        if(Y=="Crossword"):
             img1 = ImageTk.PhotoImage(file="logos/Mobama.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Obama.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Sadhguru.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/ikigai.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Raavan.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Meluha.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Crossword.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Michelle obama")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Obama")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sadhguru")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="ikigai")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Raavan")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Meluha")
        elif(Y=="Peter England"):
             img1 = ImageTk.PhotoImage(file="logos/Greenkurta.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Pocketsquare.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Navytie.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Brownkurta.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Navyjeans.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Olivewallet.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/PeterEngland.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Green kurta")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Pocketsquare")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Navy tie")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Brown kurta")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Navy jeans")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Olive wallet")
        elif(Y=="Myo Thai Spa"):
             img1 = ImageTk.PhotoImage(file="logos/Thaimassage.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Swedishmassage.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Deeptissuemassage.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img = ImageTk.PhotoImage(file="logos/comp/MyoThaiSpa.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Thai massage")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Swedish massage")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Deep tissue massage")
        

elif(d=="Female"):
    if(c=="0 to 2"):
        if(Y=="Hamleys"):
             img1 = ImageTk.PhotoImage(file="logos/Mermaid.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Barbiedoll.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Ken.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Dreamplane.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Pegasus.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Teaparty.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Hamleys.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Mermaid")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Barbie doll")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Ken")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Dream plane")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Pegasus")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Teaparty")
        elif(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/Unicorndome.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Goldcactus.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Unicornstable.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/RideonRed.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/ReginaldRhino.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Avamouse.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Unicorndome")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Gold cactus")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Unicorn stable")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Rideon Red")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Reginald Rhino")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Avamouse")
        elif(Y=="Mothercare"):
             img1 = ImageTk.PhotoImage(file="logos/Safari.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/penguinpajamas.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/explore.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/teddybearpajamas.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/sweetdreams.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/disneyshirt.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Mothercare.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Safari")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Penguin pajamas")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Explore")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Teddybear pajamas")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Sweetdreams")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Disney shirt")
        
    elif(c=="3 to 7"):
        if(Y=="Hamleys"):
             img1 = ImageTk.PhotoImage(file="logos/Weazelball.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Unojunior.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Harrypotter.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jenga.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Pinkpoodle.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Mindthegap.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Hamleys.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Weazelball")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Unojunior")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Harry potter")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jenga")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Pink poodle")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Mind the gap")
        elif(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/Snailsnails.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Loopcar.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Avamouse.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Cactusbowl.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Llamaframe.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Dinosaurs.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Snails nails")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Loopcar")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Avamouse")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Cactus bowl")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Llama frame")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Dinosaurs")
        elif(Y=="Mothercare"):
             img1 = ImageTk.PhotoImage(file="logos/Wovenred.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/dropwaist.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/explore.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Navywoven.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Pinkstripped.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/disneyshirt.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Mothercare.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Woven red")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Dropwaist")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Explore")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Navy woven")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Pink stripped")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Disney shirt")
    
    elif(c=="8 to 14"):
        if(Y=="Hamleys"):
             img1 = ImageTk.PhotoImage(file="logos/Elsabag.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Unojunior.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Pictionary.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jenga.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Pinkpoodle.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Ostrich.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Hamleys.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Elsabag")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Unojunior")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Pictionary")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jenga")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Pink poodle")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Ostrich")
        elif(Y=="Kidzone"):
             img1 = ImageTk.PhotoImage(file="logos/Parklife.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Navystar.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Avamouse.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Cactusbowl.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Llamaframe.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Dinorock.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Kidzone.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Parklife")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Navystar")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Avamouse")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Cactus bowl")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Llama frame")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Dinorock")
        elif(Y=="Max"):
             img1 = ImageTk.PhotoImage(file="logos/Floralprint.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Typographic.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Leggings.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Flamingo.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Shorts.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img = ImageTk.PhotoImage(file="logos/comp/Max.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Floral print")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Typographic")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Leggings")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Flamingo")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Shorts")
        

    elif(c=="15 to 21"):
        if(Y=="Westside"):
             img1 = ImageTk.PhotoImage(file="logos/Pinafore.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Turtleneck.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Printskirt.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Sevytop.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Plazzo.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Jessiedress.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Westside.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Pinafore")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Turtleneck")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Print skirt")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Sevy top")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Plazzo")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Jessie dress")
        elif(Y=="Inox"):
             img1 = ImageTk.PhotoImage(file="logos/Movieludo.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Movieblackwidow.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/popcorn.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Combo.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/Inox.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Movie Ludo")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Movie Blackwidow")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Popcorn")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Combo")
        elif(Y=="Nyka"):
             img1 = ImageTk.PhotoImage(file="logos/Vinegarfacewash.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Aloeveragel.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Galacticlipglass.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Lipcolor.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Matchmaster.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Mattelipstick.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Nyka.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Vinegar facewash")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Aloevera gel")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Galactic lipglass")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Lip color")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Matchmaster")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Matte lipstick")
        
            
    elif(c=="22 to 32"):
        if(Y=="H&M"):
             img1 = ImageTk.PhotoImage(file="logos/Wrapdress.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Patterneddress.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Kaftan.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jerseycrepe.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Cottoncrepe.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Jessiedress.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/H&M.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Wrapdress")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Patterned dress")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Kaftan")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jersey crepe")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Cotton crepe")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Jessie dress")
        elif(Y=="Zara"):
             img1 = ImageTk.PhotoImage(file="logos/Cullotejeans.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Totebag.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Caiajeans.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Widelegjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Vintageslim.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Sculptjeans.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Zara.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Cullote jeans")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Tote bag")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Caia jeans")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Wideleg jeans")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Vintage slim")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Sculpt jeans")
        elif(Y=="Louis Vuitton"):
             img1 = ImageTk.PhotoImage(file="logos/Onthago.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Escale.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Neonoe.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Lockmebucket.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Souple.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Chapeau.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/LouisVuitton.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Onthago")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Escale")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Neonoe")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Lockme bucket")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Souple")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Chapeau")
    
    elif(c=="33 to 45"):
        if(Y=="Zara"):
             img1 = ImageTk.PhotoImage(file="logos/Cullotejeans.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Totebag.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Caiajeans.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Widelegjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Disneysweatshirt.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Neoprene.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Zara.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Cullote jeans")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Tote bag")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Caia jeans")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Wideleg jeans")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Disney sweatshirt")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Neoprene")
        elif(Y=="Armani"):
             img1 = ImageTk.PhotoImage(file="logos/Silktop.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Vnecktop.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Shortjacket.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Cottontshirt.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Palazzo.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Organzatop.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Armani.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Silktop")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Vnecktop")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Short jacket")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Cottont shirt")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Palazzo")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Organza top")
        elif(Y=="H&M"):
             img1 = ImageTk.PhotoImage(file="logos/Wrapdress.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Patterneddress.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Kaftan.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Jerseycrepe.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Cottoncrepe.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Jessiedress.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/H&M.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Wrapdress")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Patterned dress")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Kaftan")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Jersey crepe")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Cotton crepe")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Jessie dress")
        
    
    elif(c=="46 to 59"):
         if(Y=="Myo Thai Spa"):
             img1 = ImageTk.PhotoImage(file="logos/Thaimassage.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Swedishmassage.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Deeptissuemassage.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img = ImageTk.PhotoImage(file="logos/comp/MyoThaiSpa.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Thai massage")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Swedish massage")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Deep tissue massage")
         elif(Y=="Starbucks"):
             img1 = ImageTk.PhotoImage(file="logos/Honeylatte.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Midnightmocha.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Mangopopper.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Kiwismoothie.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img = ImageTk.PhotoImage(file="logos/comp/Starbucks.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Honey latte")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Midnight mocha")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Mango popper")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Kiwi smoothie")
         elif(Y=="Zara"):
             img1 = ImageTk.PhotoImage(file="logos/Cullotejeans.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Totebag.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Caiajeans.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Widelegjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Disneysweatshirt.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Neoprene.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Zara.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Cullote jeans")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Tote bag")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Caia jeans")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Wideleg jeans")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Disney sweatshirt")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Neoprene")
        
        
    elif(c=="60 and above"):
        if(Y=="Myo Thai Spa"):
             img1 = ImageTk.PhotoImage(file="logos/Thaimassage.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Swedishmassage.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Deeptissuemassage.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img = ImageTk.PhotoImage(file="logos/comp/MyoThaiSpa.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Thai massage")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Swedish massage")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Deep tissue massage")
        elif(Y=="Crossword"):
             img1 = ImageTk.PhotoImage(file="logos/Mobama.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Obama.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Sadhguru.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/ikigai.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Raavan.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Meluha.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Crossword.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Michelle obama")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Obama")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Sadhguru")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="ikigai")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Raavan")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Meluha")
        elif(Y=="Zara"):
             img1 = ImageTk.PhotoImage(file="logos/Contrastingtrousers.jpg")
             canvas.create_image(10, 380, anchor='nw', image=img1)
             img2 = ImageTk.PhotoImage(file="logos/Totebag.jpg")
             canvas.create_image(260, 380, anchor='nw', image=img2)
             img3 = ImageTk.PhotoImage(file="logos/Caiajeans.jpg")
             canvas.create_image(540, 380, anchor='nw', image=img3)
             img4 = ImageTk.PhotoImage(file="logos/Widelegjeans.jpg")
             canvas.create_image(10, 530, anchor='nw', image=img4)
             img5 = ImageTk.PhotoImage(file="logos/Trousers.jpg")
             canvas.create_image(260, 530, anchor='nw', image=img5)
             img6 = ImageTk.PhotoImage(file="logos/Neoprene.jpg")
             canvas.create_image(540, 530, anchor='nw', image=img6)
             img = ImageTk.PhotoImage(file="logos/comp/Zara.jpg")
             canvas.create_image(200, 60, anchor='nw', image=img)
             canvas.create_text(60,510,fill="white",font="Montserrat 10 bold",text="Contrasting trousers")
             canvas.create_text(310,510,fill="white",font="Montserrat 10 bold",text="Tote bag")
             canvas.create_text(590,510,fill="white",font="Montserrat 10 bold",text="Caia jeans")
             canvas.create_text(60,660,fill="white",font="Montserrat 10 bold",text="Wideleg jeans")
             canvas.create_text(310,660,fill="white",font="Montserrat 10 bold",text="Trousers")
             canvas.create_text(590,660,fill="white",font="Montserrat 10 bold",text="Neoprene")
        
root.mainloop()

df.to_csv('project.csv',mode='a',header=False,index=False)